### ISSUE TITLE
Load Twitter following data through backend

### ISSUE THREAD

**Issue by david-mccoy** [david-mccoy/fast-feed#7]

**Comment by jdbenger** [comment]
Difficulty with acquiring the API tokens, had to register app with Twitter. Was able to get bearer token so that FastFeed has read-only access to all public data on Twitter. Generated API tokens for developer account, can now read/write Twitter data. 

Still having trouble with authorization, not sure the best way to store user access tokens once they are acquired. 3-Legged authorization uses the phones built in permissions and credentials vault to grant FastFeed access to the user tokens. 

Should determine if Firebase is a suitable storage location for user tokens.

**Comment by jdbenger** [comment]
Made public tweets search function with bearer token 
Updated the getFollowers function for user accounts
Made username search function

**Comment by jdbenger** [comment]
Functions for pulling data from Twitter are functional.
